import type { ScheduleDay } from "@/types";

export const scheduleData: ScheduleDay[] = [
  {
    date: "Saturday 16th May 2026",
    theme: "Men's Health & Teenage Health",
    sessions: [
      {
        id: "day1-registration",
        time: "8:00am",
        title: "Registration",
        type: "registration",
      },
      {
        id: "day1-intro",
        time: "8:30am",
        title: "Introduction",
        type: "opening",
        speakerSlugs: ["david-jehring"],
      },
      {
        id: "day1-richard-johnson",
        time: "8:45am",
        title: "Evolution, Nature and Diet: Insights into the Cause of the Obesity Epidemic",
        type: "talk",
        speakerSlugs: ["richard-j-johnson"],
      },
      {
        id: "day1-david-unwin",
        time: "9:30am",
        title: "Ten Manly Miracles",
        type: "talk",
        speakerSlugs: ["david-unwin"],
      },
      {
        id: "day1-break-1",
        time: "10:15am",
        title: "Break",
        type: "break",
      },
      {
        id: "day1-steve-bennett",
        time: "10:30am",
        title: "Fit and Healthy at Sixty",
        type: "talk",
        speakerSlugs: ["steve-bennett"],
      },
      {
        id: "day1-robson-kanu",
        time: "10:50am",
        title: "From Premiership Footballer to Wellness Entrepreneur",
        type: "talk",
        speakerSlugs: ["thomas-hal-robson-kanu"],
      },
      {
        id: "day1-mens-panel",
        time: "11:15am",
        title: "Men's Health Panel",
        type: "panel",
        chairSlug: "richard-smith",
      },
      {
        id: "day1-lunch",
        time: "12:30pm",
        title: "Lunch",
        type: "lunch",
      },
      {
        id: "day1-real-food",
        time: "1:30pm",
        title: "Real Food Rebellion",
        type: "talk",
        speakerSlugs: ["chris-hill", "david-sogan"],
      },
      {
        id: "day1-henry-wood",
        time: "2:15pm",
        title:
          "Real Food, Real Control: What We Eat Shapes How We Think, Feel and Perform",
        type: "talk",
        speakerSlugs: ["henry-wood"],
      },
      {
        id: "day1-break-2",
        time: "2:45pm",
        title: "Break",
        type: "break",
      },
      {
        id: "day1-paul-reynolds",
        time: "3:00pm",
        title: "Glycaemic Load and Inflammation Affects Mental Health in Teens",
        type: "talk",
        speakerSlugs: ["paul-reynolds"],
      },
      {
        id: "day1-teen-panel",
        time: "3:45pm",
        title: "Teenage Health Panel",
        type: "panel",
        chairSlug: "ruth-seymour",
      },
      {
        id: "day1-end",
        time: "5:00pm",
        title: "End of Day 1",
        type: "closing",
      },
      {
        id: "day1-dinner",
        time: "7:00pm",
        title: "Evening Fundraiser Dinner",
        type: "dinner",
        description: "Tickets to be bought separately.",
      },
    ],
  },
  {
    date: "Sunday 17th May 2026",
    theme: "Women's Health & Dietary Guidelines",
    sessions: [
      {
        id: "day2-registration",
        time: "8:00am",
        title: "Registration",
        type: "registration",
      },
      {
        id: "day2-intro",
        time: "8:30am",
        title: "Introduction",
        type: "opening",
        speakerSlugs: ["david-jehring"],
      },
      {
        id: "day2-louise-newson",
        time: "8:45am",
        title: "Hormones and Why Do We Need Them",
        type: "talk",
        speakerSlugs: ["louise-newson"],
      },
      {
        id: "day2-isabella-cooper",
        time: "9:30am",
        title: "The Effect of Suppressing Ketosis on GKI and Liver Biomarkers in Healthy Females",
        type: "talk",
        speakerSlugs: ["isabella-cooper"],
      },
      {
        id: "day2-break-1",
        time: "10:15am",
        title: "Break",
        type: "break",
      },
      {
        id: "day2-wafaa",
        time: "10:30am",
        title:
          "Rethinking Physiology: The Dynamic Interplay between Hormones, Immunity & Metabolism",
        type: "talk",
        speakerSlugs: ["wafaa-abdel-hadi"],
      },
      {
        id: "day2-womens-panel",
        time: "11:15am",
        title: "Women's Health Panel",
        type: "panel",
        chairSlug: "davinia-taylor",
      },
      {
        id: "day2-lunch",
        time: "12:30pm",
        title: "Lunch",
        type: "lunch",
      },
      {
        id: "day2-david-jehring",
        time: "1:30pm",
        title: "Elevate: Your Health Journey, Simplified",
        type: "talk",
        speakerSlugs: ["david-jehring"],
      },
      {
        id: "day2-break-2",
        time: "2:30pm",
        title: "Break",
        type: "break",
      },
      {
        id: "day2-nina-teicholz",
        time: "2:45pm",
        title: "The New USDA Dietary Guidelines",
        type: "talk",
        speakerSlugs: ["nina-teicholz"],
      },
      {
        id: "day2-guidelines-panel",
        time: "3:30pm",
        title: "Dietary Guidelines Panel",
        type: "panel",
        description: "Chair to be confirmed",
        panelistSlugs: ["nina-teicholz", "richard-j-johnson", "david-unwin"],
      },
      {
        id: "day2-end",
        time: "5:00pm",
        title: "End of Conference",
        type: "closing",
      },
    ],
  },
];
